name: Antibytes CI - Pull-Request Validation

on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches:
      - main
      - feature/*
      - release/*
      - core/*
      - plugin/*
      - bugfix/*
  workflow_dispatch:

jobs:
  build-linux:
    uses: bitpogo/workflows/.github/workflows/shared-build-linux.yml@main
    concurrency:
      group: build-linux-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  build-macos:
    uses: bitpogo/workflows/.github/workflows/shared-build-macos.yml@main
    concurrency:
      group: build-macos-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  coding-conventions:
    needs: build-linux
    uses: bitpogo/workflows/.github/workflows/shared-coding-conventions-linux.yml@main
    with:
      cache-reports: false
    concurrency:
      group: coding-conventions-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  check:
    needs: [ build-macos, build-linux ]
    uses: bitpogo/workflows/.github/workflows/shared-test-kmp.yml@main
    with:
      platforms: "['ios', 'macos', 'tvos', 'watchos', 'linux-js', 'mingw']"
    concurrency:
      group: check-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  coverage:
    needs: coding-conventions
    uses: bitpogo/workflows/.github/workflows/shared-coverage-linux.yml@main
    with:
      verify-kmp: true
      restore-cached-reports: false
    concurrency:
      group: coverage-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true

  publish:
    needs: [coverage, check]
    uses: bitpogo/workflows/.github/workflows/shared-publish-pull-request.yml@main
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
    concurrency:
      group: publish-${{ github.workflow }}-${{ github.head_ref }}
      cancel-in-progress: true
