name: Antibytes CI - Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  check:
    uses: bitpogo/workflows/.github/workflows/shared-kmp-check.yml@main
    with:
      platforms: "['android', 'ios', 'linux', 'js', 'jvm']"

  docs:
    uses: bitpogo/workflows/.github/workflows/shared-mkdocs-release.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: [check, docs]
    uses: bitpogo/workflows/.github/workflows/shared-release-validation.yml@main
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
      ossr-username: ${{ secrets.OSSR_USERNAME }}
      ossr-token: ${{ secrets.OSSR_PASSWORD }}
