name: Antibytes CI - Publish Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    uses: bitpogo/workflows/.github/workflows/shared-build-linux.yml@main
    concurrency:
      group: build-linux
      cancel-in-progress: true

  build-macos:
    uses: bitpogo/workflows/.github/workflows/shared-build-macos.yml@main
    concurrency:
      group: build-macos
      cancel-in-progress: true

  check:
    needs: [ build-macos, build-linux ]
    uses: bitpogo/workflows/.github/workflows/shared-test-kmp.yml@main
    with:
      cleanup: false
      platforms: "['apple', 'linux-all', 'mingw']"
    concurrency:
      group: check
      cancel-in-progress: true

  docs:
    needs: check
    uses: bitpogo/workflows/.github/workflows/shared-mkdocs-release.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: docs
      cancel-in-progress: true

  publish:
    needs: [check, docs]
    uses: bitpogo/workflows/.github/workflows/shared-publish-release.yml@main
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
      ossr-username: ${{ secrets.OSSR_USERNAME }}
      ossr-password: ${{ secrets.OSSR_PASSWORD }}
    concurrency:
      group: publish
      cancel-in-progress: true
