name: Antibytes CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

jobs:
  check:
    uses: bitpogo/workflows/.github/workflows/shared-test-kmp.yml@main
    with:
      platforms: "['android', 'ios',  'js', 'jvm', 'linux', 'macos', 'mingw', 'tvos', 'watchos']"
    concurrency:
      group: check-snapshot
      cancel-in-progress: true

  docs:
    uses: bitpogo/workflows/.github/workflows/shared-mkdocs-snapshot.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}

  snapshot:
    needs: [check, docs]
    uses: bitpogo/workflows/.github/workflows/shared-snapshot.yml@main
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
    concurrency:
      group: validation-snapshot
      cancel-in-progress: true
