name: Antibytes CI - Latest Version

on:
  push:
    branches:
      - main
      - release/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  build-linux:
    uses: bitpogo/workflows/.github/workflows/shared-build-linux.yml@main
    concurrency:
      group: build-linux
      cancel-in-progress: true

  build-macos:
    uses: bitpogo/workflows/.github/workflows/shared-build-macos.yml@main
    concurrency:
      group: build-macos
      cancel-in-progress: true

  coding-conventions:
    needs: build-linux
    uses: bitpogo/workflows/.github/workflows/shared-coding-conventions-linux.yml@main
    with:
      cache-reports: false
    concurrency:
      group: coding-conventions
      cancel-in-progress: true

  check:
    needs: [ build-macos, build-linux ]
    uses: bitpogo/workflows/.github/workflows/shared-test-kmp.yml@main
    with:
      platforms: "['ios', 'macos', 'tvos', 'watchos', 'linux-js', 'mingw']"
    concurrency:
      group: check
      cancel-in-progress: true

  coverage:
    needs: coding-conventions
    uses: bitpogo/workflows/.github/workflows/shared-coverage-linux.yml@main
    with:
      verify-kmp: true
      restore-cached-reports: true
    concurrency:
      group: coverage
      cancel-in-progress: true

  docs:
    needs: [ coverage, check ]
    uses: bitpogo/workflows/.github/workflows/shared-mkdocs-snapshot.yml@main
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
    concurrency:
      group: docs
      cancel-in-progress: true

  publish:
    needs: [ coverage, check ]
    uses: bitpogo/workflows/.github/workflows/shared-publish-snapshot.yml@main
    secrets:
      upload-username: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_USERNAME }}
      upload-token: ${{ secrets.PACKAGE_REGISTRY_UPLOAD_TOKEN }}
      maven-key: ${{ secrets.MAVEN_GPG_KEY }}
      maven-pass: ${{ secrets.MAVEN_GPG_PASS }}
    concurrency:
      group: publish
      cancel-in-progress: true
